export const movieSeed1 = {
  _id: 1,
  netzkinoId: 1,
  slug: "movie-1",
  title: "Movie 1",
  year: ["2022"],
  regisseur: ["Director 1"],
  stars: ["Star 1", "Star 2"],
  overview: "This is movie 1",
  imgNetzkino: "image1.jpg",
  imgNetzkinoSmall: "image1-small.jpg",
  posterImdb: "poster1.jpg",
  backdropImdb: "backdrop1.jpg",
  queries: ["action"],
  dateFetched: "2024-02-11",
  savedBy: [],
};
export const movieSeed2 = {
  _id: 2,
  netzkinoId: 2,
  slug: "movie-2",
  title: "Movie 2",
  year: ["2023"],
  regisseur: ["Director 2"],
  stars: ["Star A", "Star B"],
  overview: "This is movie 2",
  imgNetzkino: "image2.jpg",
  imgNetzkinoSmall: "image2-small.jpg",
  posterImdb: "poster2.jpg",
  backdropImdb: "backdrop2.jpg",
  queries: ["action"],
  dateFetched: "2024-02-12",
  savedBy: ["tester"],
};
export const movieSeed3 = {
  _id: 3,
  netzkinoId: 3,
  slug: "movie-3",
  title: "Movie 3",
  year: ["2024"],
  regisseur: ["Director 3"],
  stars: ["Star X", "Star Y"],
  overview: "This is movie 3",
  imgNetzkino: "image3.jpg",
  imgNetzkinoSmall: "image3-small.jpg",
  posterImdb: "poster3.jpg",
  backdropImdb: "backdrop3.jpg",
  queries: ["drama"],
  dateFetched: "2024-02-13",
  savedBy: [],
};
export const newMovie = {
  _id: 4,
  netzkinoId: 4,
  slug: "movie-4",
  title: "Movie 4",
  year: ["2025"],
  regisseur: ["Director 4"],
  stars: ["Star 4"],
  overview: "This is movie 4",
  imgNetzkino: "image4.jpg",
  imgNetzkinoSmall: "image4-small.jpg",
  posterImdb: "poster4.jpg",
  backdropImdb: "backdrop4.jpg",
  queries: ["thriller"],
  dateFetched: "2024-02-14",
  savedBy: ["user1"],
};
export const newMovies = [
  {
    _id: 5,
    netzkinoId: 5,
    slug: "movie-5",
    title: "Movie 5",
    year: ["2026"],
    regisseur: ["Director 5"],
    stars: ["Star 5"],
    overview: "This is movie 5",
    imgNetzkino: "image5.jpg",
    imgNetzkinoSmall: "image5-small.jpg",
    posterImdb: "poster5.jpg",
    backdropImdb: "backdrop5.jpg",
    queries: ["comedy"],
    dateFetched: "2024-02-15",
    savedBy: [],
  },
  {
    _id: 6,
    netzkinoId: 6,
    slug: "movie-6",
    title: "Movie 6",
    year: ["2027"],
    regisseur: ["Director 6"],
    stars: ["Star 6"],
    overview: "This is movie 6",
    imgNetzkino: "image6.jpg",
    imgNetzkinoSmall: "image6-small.jpg",
    posterImdb: "poster6.jpg",
    backdropImdb: "backdrop6.jpg",
    queries: ["drama"],
    dateFetched: "2024-02-16",
    savedBy: ["user2"],
  },
];
